version: '3.3'
services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - mynetwork
    command: --default-authentication-plugin=mysql_native_password
    environment:
      # 默认root密码，仅首次运行有效
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: qa_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - 13306:80
    environment:
      # 指定要连接的数据库，使用MySQL的容器名称
      - PMA_HOST=mysql
      # 指定要连接数据库的端口
      - PMA_PORT=3306
    depends_on:
      # 依赖MySQL容器
      - mysql
    networks:
      - mynetwork
    restart: always


networks:
  mynetwork: